### ISSUE TITLE
Optional email field is not really

### ISSUE THREAD

**Issue by rclay83** [ostyn/regretless-life#2]
Comments blew up in my face when I tried to submit a comment without my email address, which is advertised as **optional**. I am very displeased with having to provide a value for this **optional** field. Please fix immediately. Thanks and eat more chocolate balls for me ;)

**Comment by ostyn** [comment]
Just saw this. Will fix, but 50/50 odds on fixing issue vs. removing "optional". :P Thanks for filing this :D

**Comment by ostyn** [comment]
Fixed and the field is now optional. Any of the other fields missing data will result in apocalyptic error messages with zero feedback on how to fix it. But I'll work on that later.
