### ISSUE TITLE
Time travelling comments

### ISSUE THREAD

**Issue by buchmiller** [ostyn/regretless-life#3]
In the "Sweden, Part 2" blog post, the comments show evidence of time travel.
Comment 1 was on 8/23/2016
Comment 2 was on 9/2/2016
Comment 3 was on 8/31/2016

Jared, you must be better at hiding the fact that you are a Time Lord.

**Comment by ostyn** [comment]
Haha, that actually derives from a known(by me) issue. I didn't think I would be the one accidentally exercising it.
Story time:
I was in a hurry when I implemented commenting and so I was just grabbing the time from the client side. Bad idea, but I haven't gotten around to fixing it. But comment ordering doesn't really care. That's just pulled from the array ordering in MongoDB.
The confusion is coming from timezones. We're a 8(ish?) hours later, thus for me it is tomorrow. So the times are "correct", from a certain point of view. 

I'm taking a refactor day on our trip soon to fix some smaller issues around the blog. This will be one of the first. Thanks for posting :)
