### ISSUE TITLE
Cannot unsubscribe

### ISSUE THREAD

**Issue by buchmiller** [ostyn/regretless-life#4]
I subscribed with two different email addresses. After receiving an email about a new blog post at both emails, I unsubscribed with one of them. When the next new blog post came, both email addresses were notified.

**Comment by ostyn** [comment]
Solid. So work in this area includes:
1. I need to make sure unsubscribing is working. 
2. I need to check for duplicates on subscribe. I've seen this happen in the past. Someone will subscribe multiple times and they'll get multiple emails. I've been avoiding this work for a little while by removing entries manually.
3. Hash the unsubscribe token. Right now it's using the Mongo ObjectId which isn't exactly random... o.O

Thanks!

**Comment by ostyn** [comment]
And for now I just manually removed the email with your middle initial. Hope that was correct ;)

**Comment by buchmiller** [comment]
This does not appear to be working still. Now when you click "Unsubscribe" from an email, there is a 500 error.

> ### Internal Server Error
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by ostyn** [comment]
Boo... At least now I'll have time to look into it properly.
